# ros_gz_bridge parameter_bridge config (Jazzy / GZ Sim 8)

# --- Core / clock, state, base control ---------------------------------------
- ros_topic_name: "/clock"
  gz_topic_name: "/world/default/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/panda_mounted_husky/model/husky/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
  lazy: true

# --- Panda joint position commands (ROS -> GZ) --------------------------------
- ros_topic_name: "/model/panda/joint/panda_joint1/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint1/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_joint2/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint2/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_joint3/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint3/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_joint4/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint4/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_joint5/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint5/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_joint6/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint6/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_joint7/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_joint7/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_finger_joint1/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_finger_joint1/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true
- ros_topic_name: "/model/panda/joint/panda_finger_joint2/cmd_pos"
  gz_topic_name: "/model/panda/joint/panda_finger_joint2/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  lazy: true

# --- Wrist RGBD (GZ -> ROS) ---------------------------------------------------
- ros_topic_name: "/panda/wrist/rgbd/image"
  gz_topic_name: "/panda/wrist/rgbd/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/panda/wrist/rgbd/depth_image"
  gz_topic_name: "/panda/wrist/rgbd/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/panda/wrist/rgbd/camera_info"
  gz_topic_name: "/panda/wrist/rgbd/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/panda/wrist/rgbd/points"
  gz_topic_name: "/panda/wrist/rgbd/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: true

# --- Husky sensors (use the short GZ topics you listed) -----------------------
- ros_topic_name: "/camera_front/image"
  gz_topic_name: "/camera_front/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/camera_front/camera_info"
  gz_topic_name: "/camera_front/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/camera_front/depth_image"
  gz_topic_name: "/camera_front/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/camera_front/points"
  gz_topic_name: "/camera_front/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/camera_down/image"
  gz_topic_name: "/camera_down/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/camera_down/camera_info"
  gz_topic_name: "/camera_down/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/camera_down/depth_image"
  gz_topic_name: "/camera_down/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/camera_down/points"
  gz_topic_name: "/camera_down/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/planar_laser/scan"
  gz_topic_name: "/planar_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: true
- ros_topic_name: "/front_laser/scan"
  gz_topic_name: "/front_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: true

- ros_topic_name: "/imu_sensor/imu"
  gz_topic_name: "/imu_sensor"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: true
