moveit_cpp:
  planning_scene_monitor_options:
    name: "planning_scene_monitor"
    robot_description: "robot_description"
    joint_state_topic: "/joint_states"
    attached_collision_object_topic: "/attached_collision_object"
    publish_planning_scene_topic: "/publish_planning_scene"
    monitored_planning_scene_topic: "/monitored_planning_scene"
    wait_for_initial_state_timeout: 10.0

  planning_pipelines:
    pipeline_names: ["ompl"]

  # Per-pipeline settings used by OMPL inside MoveIt
  ompl:
    plugin: "ompl_interface/OMPLPlanner"
    request_adapters:
      - default_planner_request_adapters/FixWorkspaceBounds
      - default_planner_request_adapters/FixStartStateBounds
      - default_planner_request_adapters/FixStartStateCollision
      - default_planner_request_adapters/FixStartStatePathConstraints
      - default_planner_request_adapters/AddTimeParameterization
    start_state_max_bounds_error: 0.1

  # Example per-request profile (optional)
  ompl_rrtc:
    plan_request_params:
      planning_attempts: 1
      planning_pipeline: ompl
      planner_id: "RRTConnectkConfigDefault"
      max_velocity_scaling_factor: 1.0
      max_acceleration_scaling_factor: 1.0
      planning_time: 1.0
