# move_group:
#   ros__parameters:
#     octomap_frame: "odom"
#     octomap_resolution: 0.05
#     max_range: 5.0

sensors:
  - sensor_plugin: "occupancy_map_monitor/PointCloudOctomapUpdater"
    sensor_name: "camera_1_pointcloud"
    point_cloud_topic: "/camera_1/points"
    max_update_rate: 1.0
    point_subsample: 1
    padding_scale: 1.0
    padding_offset: 0.1
    filtered_cloud_topic: "/camera_1/filtered_points"

  - sensor_plugin: "occupancy_map_monitor/DepthImageOctomapUpdater"
    sensor_name: "camera_2_depth_image"
    image_topic: "/camera_2/depth/image_raw"
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 5.0
    shadow_threshold: 0.2
    padding_scale: 1.0
    padding_offset: 0.0
    max_update_rate: 1.0
    filtered_cloud_topic: "/camera_2/filtered_points"
