
  ## Properties of incoming commands
  command_in_type: "speed_units"  # "unitless" or "speed_units"
  scale:
    linear: 0.4
    rotational: 0.8
    joint: 0.5

  ## Properties of outgoing commands
  publish_period: 0.01
  low_latency_mode: false
  command_out_type: trajectory_msgs/JointTrajectory
  publish_joint_positions: true
  publish_joint_velocities: true
  publish_joint_accelerations: false

  ## Plugins for smoothing
  smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"
  low_pass_filter_coeff: 1.05

  ## MoveIt properties
  move_group_name: panda_arm
  planning_frame: panda_link0

  ## Other frames
  ee_frame_name: panda_hand_tcp
  robot_link_command_frame: panda_link0

  ## Stopping behaviour
  incoming_command_timeout: 0.25
  num_outgoing_halt_msgs_to_publish: 1

  ## Singularity & joint limit handling
  lower_singularity_threshold: 20.0
  hard_stop_singularity_threshold: 50.0
  joint_limit_margin: 0.087267

  ## Topics
  cartesian_command_in_topic: /delta_twist_cmds
  joint_command_in_topic: /delta_joint_cmds
  joint_topic: /joint_states
  status_topic: ~/status
  command_out_topic: /joint_trajectory_controller/joint_trajectory

  ## Collision checking
  check_collisions: true
  collision_check_rate: 10.0
  collision_check_type: threshold_distance
  self_collision_proximity_threshold: 0.03
  scene_collision_proximity_threshold: 0.05
  collision_distance_safety_factor: 10.0
  min_allowable_collision_distance: 0.025
