ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true
    print_diagnostics: true

    # Wheel odometry (position + linear velocity only)
    odom0: /husky_velocity_controller/odom
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 50
    #          x     y     z   roll  pitch yaw  vx    vy    vz   vroll vp    vyaw  ax    ay    az
    odom0_config: [true, true, false, false, false, false, true, false, false, false, false, false, false, false, false]

    # IMU (yaw + yaw-rate)
    imu0: /imu_sensor/imu
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 50
    imu0_remove_gravitational_acceleration: true
    #          x     y     z   roll  pitch yaw  vx    vy    vz   vroll vp    vyaw  ax    ay    az
    imu0_config:  [false,false,false, false,false,true, false,false,false, false,false,true, false,false,false]

    # (Optional, but helps reject bad readings in sim)
    odom0_pose_rejection_threshold: 2.0  # rad/m
    odom0_twist_rejection_threshold: 1.0  # m/s or rad/s
